version: '3.8'

services:
  postgres:
    container_name: coaching-postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: "test_7"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: coaching-backend
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "postgres"
      DATABASE_NAME: "test_7"
      PERSISTAUTHORIZATION: "true"
      PORT: "3001"
    command: >
      sh -c "npm install &&
             npm run migration:run &&
             npm run start:prod"
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    container_name: coaching-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    command: npm run dev -- --host

volumes:
  postgres-data: